# 异常处理

## Java虚拟机的异常处理逻辑

对于方法中的一段可能发生异常的代码，可以通过throw的方式抛出异常，交给方法的调用者处理，也可以try-catch语句捕获异常，在方法内进行处理。

对于一个方法使用throw抛出的异常，Java虚拟机首先会查找方法内部的异常处理表（这个是根据try-catch语句生成的），看看能否处理。那么有一个疑惑是说，既然选择了抛出异常，那么
方法内部应该是没有使用try-catch块处理该异常的逻辑，那么为什么还要往方法内部找？正如[ThrowAndCatch](./ThrowAndCatch.java)类的catchAndThrowIt()方法看到的那样，对于同一行可能发生
异常的代码，还可以一边抛，一边抓，在我看来，这是语文找语病里面的重复罗嗦，正因为如此，才需要先往方法内部找异常处理逻辑。如果内部找到了相应的异常处理块，就直接处理了。

如果方法内部找不到异常处理逻辑，那么Java虚拟机会查看方法的调用者中的异常处理表，如果找不到，这个过程会一直继续下去，直到找到某个异常处理项进行处理，程序得以继续运行，或者到达Java虚拟机栈的底部，最终以异常的方式终结程序。